### ISSUE TITLE
The "U.S. Phone Numbers" example can produce invalid numbers #pedantry

### ISSUE THREAD

**Issue by runnerpack** [omarroth/jager#1]
In the U.S., neither area codes nor prefixes are allowed to start with a zero, and area codes can't start with a one, have a one as their 3rd digit, or have a nine as their second digit.
(Sources: https://en.wikipedia.org/wiki/North_American_Numbering_Plan https://www.worldatlas.com/na/us/area-codes.html)

Thus, the example should read:
/[2-9][0-1][02-9]-[1-9]\d{2}-\d{4}/

(Although, actually, the 2nd and 3rd digits of the area code should never be the same, except for special cases, but that would be _much_ more verbose to encode in a regular expression…)

This project is intriguing!  Thank you for making and sharing it!

**Comment by omarroth** [comment]
Thanks for your interest.

I would recommend re-implementing this if you plan on using it for anything yourself. The approach in this library is a poorly-informed implementation based on parser actions.

If anyone is curious on how something like this would be implemented **correctly** I would recommend reading Russ Cox's series of posts, and convert a regular expression into a proper DFA as described [here](https://swtch.com/~rsc/regexp/regexp1.html). Then this library reduces to traversing the DFA randomly until reaching an accept state.
